---
title: "Interesting Forecasting Applications with R"
author: "Muhammed Ikbal Baykal - IE360 - Fall 2020"
---
```{r,echo=FALSE,results="hide"}
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
```

1. [Time series forecasting using ARIMA models](https://blogs.oracle.com/datascience/introduction-to-forecasting-with-arima-in-r)

    This example is important because it introduces the forecasting methodology using ARIMA models in R. The steps are ...

2. [Time series forecasting using ARIMA models](https://blogs.oracle.com/datascience/introduction-to-forecasting-with-arima-in-r)

    This example is important because it introduces the forecasting methodology using ARIMA models in R. The steps are ...
    
3. [Time series forecasting using ARIMA models](https://blogs.oracle.com/datascience/introduction-to-forecasting-with-arima-in-r)

    This example is important because it introduces the forecasting methodology using ARIMA models in R. The steps are ...

4. [Time series forecasting using ARIMA models](https://blogs.oracle.com/datascience/introduction-to-forecasting-with-arima-in-r)

    This example is important because it introduces the forecasting methodology using ARIMA models in R. The steps are ...
    
5. [Time series forecasting using ARIMA models](https://blogs.oracle.com/datascience/introduction-to-forecasting-with-arima-in-r)

    This example is important because it introduces the forecasting methodology using ARIMA models in R. The steps are ...