---
title: "Homework3"
author: "Muhammed Ikbal Baykal - IE360 - Fall 2020"
output: html_document
---

```{r, eval = TRUE, error=FALSE, warning=FALSE, message = FALSE, fig.width = 12, include = TRUE}
library(ggplot2)
library(zoo)
library(data.table)
library(fpp2)
library(GGally)
library(readxl)
library(corrplot)

setwd("C:/Users/90533/Desktop")
mydata<-read_excel("EVDS (3).xlsx")
```



```{r, eval = TRUE, error=FALSE, warning=FALSE, message = FALSE, fig.width = 12, include = TRUE}
mydata$Tarih<-as.Date(mydata$Tarih, format="%y/%m/½d")
data_16 <- mydata[ year(mydata$Tarih) == 2015  , ]
data_16 <- mydata[ year(mydata$Tarih) == 2016  , ]
data_17 <- mydata[ year(mydata$Tarih) == 2017  , ]
data_18 <- mydata[ year(mydata$Tarih) == 2018  , ]
data_19 <- mydata[ year(mydata$Tarih) == 2019  , ]
data_20 <- mydata[ year(mydata$Tarih) == 2020  , ]
colnames(mydata) = c("Date", "Mortgaged House Sale Statistics", "Total House Sale Statistics", "Interest Rate For House Credits", "Interest Rate", "House Price Index", "Unit House Prices", "Consumer Price Index")
head(mydata, 5)
colnames(mydata)
summary(mydata)

ggpairs(mydata[,-1])

ggplot(mydata) + geom_line(aes(x=Date, y=`Mortgaged House Sale Statistics`/5000), color="lightblue") + geom_line(aes(x=Date, y=`Interest Rate For House Credits`), color="darkblue") + theme(legend.position = "right") + theme_classic()

plot(zoo(mydata[,-1]))

ggplot(mydata) + geom_smooth(aes(x=Date, y=`Mortgaged House Sale Statistics`/5000), color="lightblue", method="lm", error=FALSE) + geom_smooth(aes(x=Date, y=`Interest Rate For House Credits`), color="darkblue", method="lm", error=FALSE) + geom_line(aes(x=Date, y=`Mortgaged House Sale Statistics`/5000), color="lightblue") + geom_line(aes(x=Date, y=`Interest Rate For House Credits`), color="darkblue") + theme(legend.position = "right") + theme_classic()

c <- cor(mydata[,-1])
corrplot(c, method="number")

# Create Training and Test data -
set.seed(100)  # setting seed to reproduce results of random sampling
trainingRowIndex <- sample(1:nrow(mydata), 0.8*nrow(mydata))  # row indices for training data
trainingData <- mydata[trainingRowIndex, ]  # model training data
testData  <- mydata[-trainingRowIndex, ]   # test data

l <- lm(formula = `Mortgaged House Sale Statistics` ~ `Interest Rate For House Credits`, data = trainingData)
prediction <- predict(l, testData )
summary(l)
```




